(()=>{
 const assetURL=p=>window.DCC_ASSETS?.[p]||p;
 const $=id=>document.getElementById(id),order=['carnage','ringmaster','riddle','milenko','jeckel','wraith','hells-pit','boom','pop','lost','found','fury','bedlam','naught','lure','wicked-vic','pug-ugly','woh'];
 const notes={carnage:'The first Joker’s Card. Its imagery and social anger establish the Carnival’s arrival.',ringmaster:'The second card’s gold-clawed overseer guides the Carnival. Here his tent becomes a frantic prize hunt.',riddle:'The third card presents a choice whose consequence is revealed when the box opens. This game turns that reveal into a collapsing-floor contest.',milenko:'The fourth card’s illusionist tempts and deceives. The game uses false prizes, haunted reflections, and breakable mirrors.',jeckel:'Jack the Sinister and Jake the Just juggle the weight of a soul’s sins. Sin Toss adapts their fire into a competitive deflection game.',wraith:'The sixth card’s Shangri-La exhibit. The Wraith is the same card across this album and Hell’s Pit.',"hells-pit":'The second exhibit of The Wraith, not a seventh card. The game contrasts the warmth of the light with its hostile pit.',boom:'The first card of the second deck. This catalog uses the Nuclear edition linked by Psychopathic.',pop:'The second card of the second deck. Its gameplay modifier makes tempting bonuses burst into the contest.',lost:'One half of the third card of the second deck. Lost and Found count as one Joker’s Card.',found:'The other half of The Marvelous Missing Link. Both exhibits belong to the same card.',fury:'The fourth card of the second deck. The game’s counterattack modifier draws on its fight-back theme.',bedlam:'The fifth card of the second deck. A tempting garden becomes valuable but dangerous ground.',naught:'The sixth card of the second deck, confirmed by Psychopathic Records and released in 2025.'};
 const esc=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 $('catalog-grid').innerHTML=order.map(id=>{const a=CATALOG.find(x=>x.id===id);return a?`<button class="album-tile" data-album="${id}"><img src="${assetURL(a.local)}" alt="${esc(a.title)} album artwork"><strong>${esc(a.title)}</strong><span>${a.tracks.length} TRACKS · OPEN LINER NOTES ↗</span></button>`:''}).join('');
 document.querySelectorAll('[data-album]').forEach(b=>b.onclick=()=>{const a=CATALOG.find(x=>x.id===b.dataset.album),dialog=$('record-dialog');dialog.innerHTML=`<button class="dialog-close" aria-label="Close album">×</button><div class="album-detail"><img class="album-art" src="${assetURL(a.local)}" alt="${esc(a.title)}"><div><p class="eyebrow">INSANE CLOWN POSSE · RECORD ARCHIVE</p><h2>${esc(a.title)}</h2><p>${notes[a.id]||'A sideshow release from the broader catalog. Its artwork and track metadata are included here; a dedicated playable attraction is not yet built.'}</p><a href="${esc(a.source)}" target="_blank" rel="noopener">Official catalog destination ↗</a><p class="album-source">Artwork and track metadata sourced from the Apple Music destination linked by Psychopathic Records. Game rules are adaptations, not quoted lore.</p></div></div><ol class="track-list">${a.tracks.map(t=>`<li><a href="${esc(t.url)}" target="_blank" rel="noopener">${esc(t.name)} <span class="listen-arrow">↗</span></a></li>`).join('')}</ol>`;dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.showModal();});
 $('record-dialog').addEventListener('click',e=>{if(e.target===$('record-dialog'))$('record-dialog').close();});
 $('tab-records').onclick=()=>{$('catalog-panel').hidden=true;$('secret-grid').hidden=false;$('tab-records').classList.add('active');$('tab-catalog').classList.remove('active');};
 $('tab-catalog').onclick=()=>{$('catalog-panel').hidden=false;$('secret-grid').hidden=true;$('tab-catalog').classList.add('active');$('tab-records').classList.remove('active');};
 $('fullscreen-button').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('game').requestFullscreen();}catch{}};
})();
